security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Bangpound\Bundle\DrupalBundle\Security\User\User:
            id: bangpound_drupal.encoder

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        bangpound_drupal:
            id: bangpound_drupal.user_provider

        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        drupal:
            pattern: ^.+$
            anonymous: ~
            logout:
                path:   user/logout
                invalidate_session: true
                handlers: [ bangpound_drupal.logout.handler ]
            form_login:
                check_path: user/login
                login_path: user
                username_parameter: name
                password_parameter: pass

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: _security_check
                login_path: _demo_login
            logout:
                path:   _demo_logout
                target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
